apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xapps.platform.upbound.io
spec:
  claimNames:
    kind: App
    plural: apps
  group: platform.upbound.io
  names:
    categories:
    - crossplane
    kind: XApp
    plural: xapps
  versions:
  - name: v1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: App is the Schema for the App API.
        properties:
          spec:
            description: AppSpec defines the desired state of App.
            properties:
              parameters:
                properties:
                  workloads:
                    properties:
                      app1:
                        properties:
                          affinity:
                            type: object
                          autoscaling:
                            properties:
                              enabled:
                                type: boolean
                              maxReplicas:
                                type: number
                              minReplicas:
                                type: number
                              targetCPUUtilizationPercentage:
                                type: number
                            type: object
                          fullnameOverride:
                            type: string
                          image:
                            properties:
                              pullPolicy:
                                type: string
                              repository:
                                type: string
                              tag:
                                type: string
                            type: object
                          imagePullSecrets:
                            items:
                              type: object
                            type: array
                          ingress:
                            properties:
                              annotations:
                                type: object
                              className:
                                type: string
                              enabled:
                                type: boolean
                              hosts:
                                items:
                                  properties:
                                    host:
                                      type: string
                                    paths:
                                      items:
                                        properties:
                                          path:
                                            type: string
                                          pathType:
                                            type: string
                                        type: object
                                      type: array
                                  type: object
                                type: array
                              tls:
                                items:
                                  type: object
                                type: array
                            type: object
                          livenessProbe:
                            properties:
                              httpGet:
                                properties:
                                  path:
                                    type: string
                                  port:
                                    type: string
                                type: object
                            type: object
                          nameOverride:
                            type: string
                          nodeSelector:
                            type: object
                          podAnnotations:
                            type: object
                          podLabels:
                            type: object
                          podSecurityContext:
                            type: object
                          readinessProbe:
                            properties:
                              httpGet:
                                properties:
                                  path:
                                    type: string
                                  port:
                                    type: string
                                type: object
                            type: object
                          replicaCount:
                            type: number
                          resources:
                            type: object
                          securityContext:
                            type: object
                          service:
                            properties:
                              port:
                                type: number
                              type:
                                type: string
                            type: object
                          serviceAccount:
                            properties:
                              annotations:
                                type: object
                              automount:
                                type: boolean
                              create:
                                type: boolean
                              name:
                                type: string
                            type: object
                          tolerations:
                            items:
                              type: object
                            type: array
                          volumeMounts:
                            items:
                              type: object
                            type: array
                          volumes:
                            items:
                              type: object
                            type: array
                        type: object
                    type: object
                type: object
            type: object
          status:
            description: AppStatus defines the observed state of App.
            type: object
        required:
        - spec
        type: object
    served: true
